### ISSUE TITLE
the program stop receiving events

### ISSUE THREAD

**Issue by amosrohe** [adamyeager/PushbulletSharp#32]
after ~20 minutes .. an hour (the time is not constant) the application stop receiving events
looking at the "https://www.pushbullet.com/#following" I can see the events (the text used ) 

the same is happening on the example you publish

the only difference is i add to use 
" ws.SslConfiguration.EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls12;"

in here 

 using (var ws = new WebSocket(string.Concat("wss://stream.pushbullet.com/websocket/", key)))
                {                    ws.SslConfiguration.EnabledSslProtocolsSystem.Security.Authentication.SslProtocols.Tls12;
                    ws.OnMessage += (sender, e) =>
                    {

or i get an SSL error

**Comment by adamyeager** [comment]
What version of .net are you using. I think 4.6 defaults to TLS 1.2 but I could be mistaken. I'll see if I can recreate this issue on my end.

**Comment by amosrohe** [comment]
4.5 on the pushbuliietsharp and 4.5.2 in the application 

the SSL is not the issue i think the "stop receiving events" is the issue 
Amos

**Comment by amosrohe** [comment]
BTW 
if i hit a key 
i will get this message ... 
"
Fatal|WebSocket.<startReceiving>b__170_2|System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
                              at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
                              at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
                              --- End of inner exception stack trace ---
                              at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
                              at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
                              at WebSocketSharp.Ext.<>c__DisplayClass54_0.<ReadBytesAsync>b__0(IAsyncResult ar)
"
